### PR TITLE
17 add some tests

### LINKED ISSUE #3: user/me and user/:id - doesn't work!
We have
```
server.get('/user/:id', forAuthorized, function (req, res, next) {
```
and
```
server.get('/user/me', forAuthorized, setUser, function (req, res, next) {
```

user/me doesn't work because we have user/:id already.

Solution:
We have to modify user/:id method, add
```
  if (req.params.id === 'me') {
    return res.send(200, req.user);
  }
```
and change
```
server.get('/user/:id', forAuthorized, function (req, res, next) {
```
to
```
server.get('/user/:id', forAuthorized, setUser, function (req, res, next) {
```

Also we have to remove user/me at all now.

----------

To make user/:id work we have to replace
```
db.collection('users').findOne({ _id: mongojs.ObjectId(req.headers['secret-token']), is_published: "true"}, function(err, doc) {
```
with 
```
db.collection('users').findOne({ _id: mongojs.ObjectId(req.params.id)}, function(err, doc) {
```

### PR DESCRIPTION
**Pull request by SleepWalker**
Merge request for #17 
It is also fixes #3, #4, #6 and #23

Bugfixes for `POST /user/me/avatar`:

- it saves avatar files under `public/avatars` instead of `public`
- added 422 error, when no avatar file supplied for /user/me/avatar

Bugfixes for `GET /user/:id`:

- using user id from request `:id` instead of token

Status codes/response formats was normalized:

- the error is always `{error: '...'}` or `{errors: [{attr: '...'}, ...]}`
- bad auth always returns 401 (not 404, as was in some cases earlier)

Other:

- Token validation now checks if we really have specified user. `setUser` middleware at the moment has no function, but it was leaved for future, when token will not be equal user id.
- Fixed copy-paste bug of request logging (we have only one middleware with `request` variable. Logging method was copied from there to other middlewares where we have `req` instead of `request`)
- Database initialization was factored out into separate module to make it possible to use it from everywhere across code.

### CODE REVIEW

**Comment by sudodoki** [comment]
Great work! Tests are failing because there's no mongo. Need to add it to .travis.yml config

**Comment by SleepWalker** [comment]
magic! It's green ^^

**Comment by sudodoki** [comment]
^_^ let me take a closer look in couple of hours

File: API_v2/index.js [hunk 1]
```diff
@@ -125,52 +131,59 @@ server.post('/signup', function (req, res, next) {
...
-  return res.send(200, req.user);
-});
-
-server.post('/user/me', forAuthorized, setUser, function (req, res, next) {
+server.post('/user/me', forAuthorized, function (req, res, next) {
   var userUpdate = { $set: req.params };
   db.collection('users').findAndModify({
     query: { _id: req.user._id},
     update: userUpdate,
+    'new': true,
```
Comment (sudodoki) [inline API_v2/index.js]: Why do you need this flag?

File: API_v2/index.js [hunk 2]
```diff
@@ -178,4 +191,10 @@ server.post('/user/me/avatar', forAuthorized, setUser, function(req, res, next){
   });
 });
 
+function handleDbError(err, res) {
```
Comment (sudodoki) [inline API_v2/index.js]: :+1:

File: API_v2/middlewares/cors.js [hunk 3]
```diff
@@ -1,4 +1,4 @@
-module.exports = function (_) {
```
Comment (sudodoki) [inline API_v2/middlewares/cors.js]: This is supposed to mitigate that there's a variable passed but never used. Assuming this one violated jshint rule?

File: API_v2/test/API/signin.test.js [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+var db = require(root + 'services/db');
+
+var endPoint = '/signin';
+
+
+describe('GET ' + endPoint, function() {
+  it('should return 404', function(done) {
+    request(app)
+      .get(endPoint)
+      .expect(204)
```
Comment (sudodoki) [inline API_v2/test/API/signin.test.js]: Should return 404 - expect(204). Something fishy going on here :D

File: API_v2/test/API/signin.test.js [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    user.password = 'angry hacker';
+
+    request(app)
+      .post(endPoint)
+      .send(user)
+      .expect(401)
+      .end(done);
+  });
+
+  it('should not user that not exists', function(done) {
```
Comment (sudodoki) [inline API_v2/test/API/signin.test.js]: should not [login] user

File: API_v2/index.js (hunk 1 above)
Comment (SleepWalker) [inline API_v2/index.js]: without this flag in callback we will have an old (not updated) doc. But we need new one!

File: API_v2/middlewares/cors.js (hunk 3 above)
Comment (SleepWalker) [inline API_v2/middlewares/cors.js]: no, I removed args because now midlewares does not need this dependency. The only thing there was configuration variable is to initialize db. Now db initialized and returned from separate module. So I decided to remove arg with config to avoid unnecessary dependencies.

File: API_v2/test/API/signin.test.js (hunk 4 above)
Comment (SleepWalker) [inline API_v2/test/API/signin.test.js]: oops :)
probably we don't need that test at all. This is the only place, where I tested forbidden verbs

File: API_v2/index.js (hunk 1 above)
Comment (sudodoki) [inline API_v2/index.js]: WUT? Do you mean to say update invokes cb with old document?

File: API_v2/test/fixtures/users.js [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+ * fixture.privateUsersList - just user (e.g. current user)
+ * fixture.publicUser - user with public available profile
+ * fixture.privateUser - user with private profile
+ */
+
+var root = '../../';
+
+var db = require(root + 'services/db');
+
+var fakeUsers = [
```
Comment (sudodoki) [inline API_v2/test/fixtures/users.js]: maybe, we could reuse https://github.com/sudodoki/api_client_test/blob/master/API_v2/scripts/fixtures.js or have fixtures in spec as common file & use it in scripts/seed.js?

File: API_v2/test/fixtures/users.js [hunk 7]
```diff
@@ -0,0 +1,125 @@
+/**
```
Comment (sudodoki) [inline API_v2/test/fixtures/users.js]: Nice touch with this spec helper :heart:

File: API_v2/index.js (hunk 1 above)
Comment (sudodoki) [inline API_v2/index.js]: Nevermind, read the doc for `findAndModify` - was missing this option.

Comment (SleepWalker) [inline API_v2/index.js]: yeah. the tests revealed the truth about what we actually get :)

Comment (sudodoki) [inline API_v2/index.js]: Oh, this power of revealing :D
10 марта 2015 г. 1:55 пользователь "Sviatoslav" <notifications@github.com>
написал:

File: API_v2/test/fixtures/users.js (hunk 6 above)
Comment (SleepWalker) [inline API_v2/test/fixtures/users.js]: I started with modifying that file. But later I was not sure if I can do that. Because in that file is old db structure (where each user is object with key `user`) and it is used for seed command, so I decided to create separate file.

The both suggested variants is good. The only reason of separate file was to protect your code from my alternations :) Probably it is better to expose users (`fakeUsers` var) from `tests/fixtures/users` and use it in the seed script.
